import { QuizPartConfig } from '../types/quiz';

export const Part1Config: QuizPartConfig = {
  id: 1,
  partName: "Part 01",
  partId: "part1",
  title: "Part 01. Profile",
  totalSteps: 6,
  defaultImages: {
    funnyFace: "/images/part1/frame-1.png",
  },
  requiredFields: [
    "fullname",
    "nickname",
    "favoriteColor",
    "wordToDescribe",
    "loveLanguage",
  ],
  steps: [
    {
      key: "funnyFace",
      type: "TaskPicture",
      question: "Make a funny face!",
      isRequired: false,
    },
    {
      key: "fullname",
      type: "QandAshort",
      question: "The name?",
      inputPlaceholder: "eg. Jose Rizal",
      isRequired: true,
    },
    {
      key: "birthday",
      type: "DatePicker",
      question: "So, when you were born?",
      isRequired: false,
    },
    {
      key: "nickname",
      type: "QandAshort",
      question: "Nickname or go-to username?",
      inputPlaceholder: "eg. DoctorJoe",
      isRequired: true,
    },
    {
      key: "favoriteColor",
      type: "QuestionAndChips",
      question: "Pick your happy crayon",
      options: [
        { label: "Red", color: "bg-red-five" },
        { label: "Blue", color: "bg-blue-five" },
        { label: "Green", color: "bg-green-five" },
        { label: "Yellow", color: "bg-yellow-five" },
        { label: "Violet", color: "bg-violet-five" },
        { label: "Orange", color: "bg-orange-five" },
        { label: "Pink", color: "bg-pink-five" },
        { label: "Brown", color: "bg-brown-five" },
        { label: "Black", color: "bg-black-five" },
        { label: "White", color: "bg-white" },
        { label: "Gray", color: "bg-gray-five" },
      ],
      isRequired: true,
    },
    {
      key: "wordToDescribe",
      type: "QuestionAndChips",
      question: "One word that describes you?",
      options: [
        { label: "Calm", color: "bg-blue-five" },
        { label: "Adventurous", color: "bg-green-five" },
        { label: "Creative", color: "bg-orange-five" },
        { label: "Mysterious", color: "bg-black-five" },
        { label: "Friendly", color: "bg-pink-five" },
        { label: "Smart", color: "bg-red-five" },
        { label: "Funny", color: "bg-yellow-five" },
        { label: "Imaginative", color: "bg-violet-five" },
        { label: "Innocent", color: "bg-white" },
      ],
      isRequired: true,
    },
    {
      key: "loveLanguage",
      type: "QuestionAndChips",
      question: "Love Language (receive)?",
      options: [
        { label: "Acts of Service", color: "bg-red-five" },
        { label: "Receiving gifts", color: "bg-blue-five" },
        { label: "Quality time", color: "bg-green-five" },
        { label: "Words of Affirmation", color: "bg-yellow-five" },
        { label: "Physical Touch", color: "bg-pink-five" },
      ],
      isRequired: true,
    },
    {
      key: "divider",
      type: "Divider",
      question: "",
      isRequired: false,
    },
    {
      key: "usernameStory",
      type: "QandAlong",
      question: "Any cool story behind the username/nickname?",
      inputPlaceholder: "Share something fun!",
      isRequired: false,
    },
    {
      key: "funFact",
      type: "QandAlong",
      question: "Random fun fact about you? Or just anything random at all.",
      inputPlaceholder: "Share something fun!",
      isRequired: false,
    },
  ],
};