import { QuizPartConfig } from '../types/quiz';

export const Part1Config: QuizPartConfig = {
  id: 1,
  partName: "Part 01",
  partId: "part1",
  title: "Part 01. Profile",
  totalSteps: 6,
  defaultImages: {
    funnyFace: "/images/part1/frame-1.png",
    bigSmile: "/images/part1/frame-2.png",
    bestLook: "/images/part1/frame-3.png",
  },
  requiredFields: [
    "favoriteColor",
    // "wordToDescribe",
    // "fullname",
    // "birthday",
  ],
  steps: [
    {
      key: "funnyFace",
      type: "TaskPicture",
      question: "Make a funny face!",
      isRequired: false,
    },
    {
      key: "fullname",
      type: "QandAshort",
      question: "Full name?",
      inputPlaceholder: "eg. Joe Stone Doctor",
      isRequired: true,
    },
    {
      key: "bigSmile",
      type: "TaskPicture",
      question: "Crack a big smile!",
      isRequired: false,
    },
    {
      key: "birthday",
      type: "DatePicker",
      question: "When's your birthday?",
      isRequired: true,
    },
    {
      key: "bestLook",
      type: "TaskPicture",
      question: "Show me your best look/pic!",
      isRequired: false,
    },
    {
      key: "favoriteColor",
      type: "QuestionAndChips",
      question: "Favorite color?",
      options: [
        { label: "Red", color: "bg-red-five" },
        { label: "Blue", color: "bg-blue-five" },
        { label: "Green", color: "bg-green-five" },
        { label: "Yellow", color: "bg-yellow-five" },
        { label: "Purple", color: "bg-violet-five" },
        { label: "Orange", color: "bg-orange-five" },
        { label: "Pink", color: "bg-pink" },
        { label: "Brown", color: "bg-brown-five" },
        { label: "Black", color: "bg-black-five" },
        { label: "White", color: "bg-white" },
        { label: "Gray", color: "bg-gray-five" },
      ],
      isRequired: true,
    },
    {
      key: "wordToDescribe",
      type: "QuestionAndChips",
      question: "One word that describes you?",
      options: [
        { label: "Calm", color: "bg-blue-five" },
        { label: "Adventurous", color: "bg-green-five" },
        { label: "Creative", color: "bg-orange-five" },
        { label: "Mysterious", color: "bg-black-five" },
        { label: "Friendly", color: "bg-pink" },
        { label: "Smart", color: "bg-red-five" },
        { label: "Funny", color: "bg-yellow-five" },
        { label: "Imaginative", color: "bg-violet-five" },
        { label: "Innocent", color: "bg-white" },
      ],
      isRequired: true,
    },
    {
      key: "divider",
      type: "Divider",
      question: "",
      isRequired: false,
    },
    {
      key: "nickname",
      type: "QandAshort",
      question: "Nickname or username?",
      inputPlaceholder: "eg. DoctorJoe",
      isRequired: false,
    },
    {
      key: "usernameStory",
      type: "QandAlong",
      question: "Any cool story behind it?",
      inputPlaceholder: "Share something fun!",
      isRequired: false,
    },
    {
      key: "funFact",
      type: "QandAlong",
      question: "Random fun fact about you? Or just anything random at all.",
      inputPlaceholder: "Share something fun!",
      isRequired: false,
    },
  ],
};